name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      docker:

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image for react-test
      run: docker build -t react-test -f ./client/Dockerfile.dev ./client

    - name: Run tests
      run: docker run -e CI=true react-test npm test

    - name: Build Docker images
      run: |
        docker build -t multi-client ./client
        docker build -t multi-nginx ./nginx
        docker build -t multi-server ./server
        docker build -t multi-worker ./worker