name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image for react-test
      run: docker build -t react-test -f ./client/Dockerfile.dev ./client

    - name: Run tests
      run: docker run -e CI=true react-test npm test

    - name: Build Docker images
      run: |
        docker build -t adakos/multi-client ./client
        docker build -t adakos/multi-nginx ./nginx
        docker build -t adakos/multi-server ./server
        docker build -t adakos/multi-worker ./worker

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_ID }} --password-stdin

    - name: Push Docker images to Docker Hub
      run: |
        docker push adakos/multi-client
        docker push adakos/multi-nginx
        docker push adakos/multi-server
        docker push adakos/multi-worker

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy to beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: multi-docker
        environment_name: Multi-docker-env
        existing_bucket_name: elasticbeanstalk-eu-north-1-211125786792
        # bucket_path: docker-multi
        region: eu-north-1
        version_label: ${{ github.sha }}
        deployment_package: deploy.zip

