name: Deploy complex
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: obuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true react-test npm test
      - run: ocker build -t multi-client ./client
      - run: docker build -t multi-nginx ./nginx
      - run: docker build -t multi-server ./server
      - run: docker build -t multi-worker ./worker
